### ISSUE TITLE
Gomobile?

### ISSUE THREAD

**Issue by whthend** [ThePlasmaRailgun/TXQR-Android#5]
Since building a front end with Flutter, why not use Gomobile?

**Comment by NovaLogicDev** [comment]
The primary directive of this project was not to use the codebase of txqr but rather to implement the idea of what txqr is. This meant avoiding the use of Go as a core language of the application which would have added problematic bloat to the application having to work in not only two but 3 different and unique languages each with special ecosystems and build tooling.
